name: Deploy Folders in wp-content/uploads/2023

on:
  push:
    branches:
      - main  # Thay bằng nhánh mặc định của bạn

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Detect changes in wp-content/uploads/2023
        id: detect
        run: |
          # Detect changes in the wp-content/uploads/2023 directory
          CHANGED_FOLDERS=$(git diff --name-only HEAD~1 HEAD | grep '^wp-content/uploads/2023/' | cut -d'/' -f5 | sort | uniq)
          echo "changed_folders=$CHANGED_FOLDERS" >> $GITHUB_ENV

      - name: Show changed folders
        run: |
          echo "Changed folders: ${{ env.changed_folders }}"

      - name: Deploy changed folders
        if: env.changed_folders
        run: |
          for folder in $CHANGED_FOLDERS; do
            echo "Deploying folder: wp-content/uploads/2023/$folder"
            # Replace the following line with your actual deployment logic
            # Example using rsync:
            rsync -av wp-content/uploads/2023/$folder/ <your-deploy-server>:/path/to/uploads/2023/$folder/
          done
